[package]
name = "flashtextr"
version = "0.1.1"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "lib"]

[dependencies.pyo3]
version = "0.14.5"
features = ["extension-module", "abi3-py36"]
